language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
  - "pypy3"
env:
  - TEST_ENV=src
  - TEST_ENV=e2e
install:
- python setup.py -q install
- pip install -r requirements.txt
script:
- cd $TEST_ENV
- pytest
jobs:
  include:
  - stage: lint
    language: python
    python: 3.6
    install:
    - pip install pylint
    - pip install -r requirements.txt
    script:
    - pylint src/frenetiq_crawler
  - stage: deploy
    language: python
    python: 3.6
    sudo: required
    dist: trusty
    install: skip
    script:
    - pip install pypandoc
    - python setup.py sdist --ci
    deploy:
      - provider: pypi
        distributions: sdist
        user: snorrwe
        password:
          secure: lhjXYNZXRhVxMbbR7/EdSHn3pNCJ8kua7XZkUrOF5Z91Uw9PXI1Qy9MTRBShJDyhBSYu3VJlbDDvEKcUxmxTeIpBoXtWRwN7vPa7v86eIi9Pm3evUATT9TYp/0QgdNM0R95Rhm0Pl9Tc6j4N0IRcJipzqqg982dgp/2CYG/nx6aEB0mz5vGnv7D8ouWn0ocwT90gZ9mXOVCkpaXQd1B21OOcXzVtmLBTjX54vraYbAcmM6YNdCysfvNn//K6a6OrjsZdzWNAnnX9CjLTJDduVPOscNYmFsd41mEXlRxatJ+iOmB86K/IMceIWwl5tzO96A/JrWUzbcxzx2GA3TaWKs4bElsLLH6oKx1F1jHakPmSk9kNdYfkLOes8tq+wnwflHHfnihqEffSLMZWXQx002hIg9Gv6/+mfzrfnQ3y0ttZDB7oV/qW59z6tLdZ3Ptf573Bcxv74SMYYt/JYG2vyMQAC0QSgr0eIA9AsU5FB6XHQOn98dOdKxd0mi9dsZiHq2Zh7GverbR5U7R9eVm31dfMWy/tC+e19MnycYgJ2GA5wEktuSjw0BCEITgozftKzhgjS1pVI95Ni4TgxPcUyDo7NAJklv39BZWIF7tJKYa6rAmIrcZFwheSWPzGb8xDaRf0gqRyh8ICq0KaWMh8oNkXwF8yPrt/iLDRlAoj+9w=
        skip_cleanup: true
        on:
          tags: true
      - provider: releases
        api_key:
          secure: X9wyuWyMdkcXA6cEYrJh332o+qNfR8xLVAUbbUGMfyPDIXWc5dUeiAvgFambdopIxwSiHBhmI4SU0TTan/tEaFbcCKr5wa2yAV2XIv7hyWbFnIHqNYTGWZTUReXLTjbsu0hWb123LxQWGfxD6ZBeDkZaQu5By45jYmhmYg9Ye/In/f3rlvnQ9s62jx/+x4jfgOY+9Hjla/wVviHAOiEhk/mCL3Tb1CbNJqptUfbB1F3ru5YxKCaEyMawJ+SXwQQAGWbXodvT2FwfwRUI6qRa0BikKGikLWhKuwO0aLupv3dIV3zulJIiw7xpkoJsX6OCgdxIQyPmqN0X1qOSdEGp7JTOr8NOmeUBOLkJdX2VbHWI6pOlt1K7sTZ0EdXI9VVRiZR48QndtKmxEr4L2ZAdY5jIegYLnswuVIFsNAhaBFUE8zHhn5MhGVjc2g6ehQggzm9TSNz8BmPAofcUda5tl8r96vn41xxaCt9AD4pPTkNHPtz9Qq5a0Hs53muGqOPmIPsW00QJLk4khVQ4LqWN7P8zMuBuP2mnfzo9rnOeP+LHlUOTXZ79vvcWIELcmov4HfIFVSz0ZxmyDgjD4PuCnVfRvncIdqbuV097awutz4eXxz8WJwm7w6EcygrA081SmqqZEFvs5fBiTVaylfLQFp0Uy4M0uGThuInQq265DNo=
        file_glob: true
        file: dist/*
        skip_cleanup: true
        on:
          tags: true
